[pytest]

# Command-line options applied automatically
addopts = -v -s
# Minimum pytest version
# Register custom ETL markers
markers =
    etl: ETL validation tests
    smoke: Smoke tests
    regression: Regression tests
    data_quality: Data quality validation tests
    reconciliation: Source-to-target reconciliation tests
    sanity : sanity tests
    functional: functional tests
    prodrelease:prod release tests

minversion = 8.0